### ISSUE TITLE
Rename sub packages for v1

### ISSUE THREAD

**Issue by JamesRamm** [JamesRamm/longclaw#154]
* longclaw version:
* Django version:
* Python version:

### Description

As wagtail has renamed its packages (e.g wagtail.wagtailadmin -> wagtail.admin), it makes sense to do the same here for compatibility with wagtail 2

**Comment by linuxluigi** [comment]
I renamed the package names for wagtail 2.x, refactor the url structure for django 2.x & update the requirements for both. It's look like that longclaw work with wagtail 2.1 but the test are still failing. I'm not sure if the tests are broken or it I forgot something.

Source: https://github.com/linuxluigi/longclaw/tree/django-wagtail-2.x

```
======================================================================
ERROR: test_get_admin (longclaw.contrib.productrequests.tests.ProductRequestTest)
Check we can retrieve the requests admin page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fubu/dev/longclaw/longclaw/contrib/productrequests/tests.py", line 8, in setUp
    self.variant = ProductVariantFactory()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/base.py", line 563, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/base.py", line 500, in _generate
    return step.build()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/builder.py", line 375, in __getattr__
    extra=context,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/declarations.py", line 324, in evaluate
    return self.generate(step, defaults)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/declarations.py", line 414, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/factory/base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/Users/fubu/dev/longclaw/longclaw/tests/utils.py", line 76, in _create
    return super(ProductFactory, cls)._create(model_class, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wagtail_factories/factories.py", line 48, in _create
    return model_class.add_root(**kwargs)
AttributeError: 'NoneType' object has no attribute 'add_root'
```

**Comment by JamesRamm** [comment]
For those interested (@linuxluigi maybe), the branch longclawv2 is now passing all tests, with the latest wagtail and python 3.x branch
I'll be doing some more checks but hope to merge in the next few days.
