### ISSUE TITLE
When will this be upgraded to work with Wagtail 2.4

### ISSUE THREAD

**Issue by mattmillen888** [JamesRamm/longclaw#215]
# Issue running python manage.py loadcountries
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/longclaw/shipping/management/commands/loadcountries.py", line 8, in handle
    call_command('loaddata', 'shipping_initial.json', app_label='shipping')
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 106, in loaddata
    if self.find_fixtures(fixture_label):
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 229, in find_fixtures
    fixture_dirs = self.fixture_dirs
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/homefolder/.virtualenvs/appname/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 288, in fixture_dirs
    "and cannot be listed in settings.FIXTURE_DIRS." % (app_dir, app_label)
django.core.exceptions.ImproperlyConfigured: '/var/www/appname/appname/fixtures' is a default fixture directory for the 'optiqueline' app and cannot be listed in settings.FIXTURE_DIRS.

**Comment by JamesRamm** [comment]
I am planning to release Longclaw v1.0.0 hopefully this weekend. (1st-3rd Feb). 
In the meantime, you can install directly from github master branch.

**Comment by JamesRamm** [comment]
Duplicate #99
