### ISSUE TITLE
Error executing  running manage.py migrate

### ISSUE THREAD

**Issue by ironexmaiden** [JamesRamm/longclaw#221]
* longclaw version:1.0.0
* Django version:2.1
* Python version:3.6

running manage.py migrate

`Operations to perform:
  Apply all migrations: admin, auth, basket, checkout, configuration, contenttypes, orders, products, sessions, shipping, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 163, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "/usr/lib64/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python3.6/site-packages/django/db/migrations/state.py", line 210, in apps
    return StateApps(self.real_apps, self.models)
  File "/usr/lib64/python3.6/site-packages/django/db/migrations/state.py", line 271, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/usr/lib64/python3.6/site-packages/django/db/migrations/state.py", line 314, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'catalog.ProductIndex'>, <ModelState: 'catalog.Product'>, <ModelState: 'home.HomePage'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/2.1/topics/migrations/#dependencies for more
`

**Comment by JamesRamm** [comment]
Hi there
Did you run makemigrations first?

`python manage.py makemigrations catalog home`

In the docs here:
https://jamesramm.github.io/longclaw/docs/tutorial/install

**Comment by JamesRamm** [comment]
@ironexmaiden did this fix the issue?

**Comment by ironexmaiden** [comment]
Yes of course, sorry for the delay considered this issue closed :) thank you
